### ISSUE TITLE
Feature-request: allow specification of headers in `loadResourceLines`

### ISSUE THREAD

**Issue by kritixilithos** [fergusq/roda#7]
This is a feature request to add the ability to specify headers (not just the User Agent) in the `loadResourceLines` command.

Perhaps something along the lines of `loadResourceLines("https://example.com/", "Authorization: Key s3crEtcode", "another_one: asdfg123567")`?

**Comment by fergusq** [comment]
I implemented this feature by adding a new keyword parameter to `loadResourceLines` and `saveResource`.

It accepts both maps and lists, using the following format:

    h := new map
    h["Authorization"] = "Key s3crEtcode"
    h["another_one"] = "asdfg1234567"
    loadResourceLines("example.com", headers=h)

    loadResourceLines("example.com", headers=["Authorization: Key s3crEtcode", "another_one: asdfg123567"])

The implementation is currently in the roda-0.14 branch.

**Comment by kritixilithos** [comment]
Thanks, the idea of using the header kwarg is works better than what I had in mind
